### ISSUE TITLE
Defines needed 

### ISSUE THREAD

**Issue by tsathoqqua** [fluffos/lima#1]
Hey,
Out of the box Lima wants:

    need("#define SANE_EXPLODE_STRING");
    need("#define NO_LIGHT");
    need("#define NO_ADD_ACTION");
    need("#define NO_WIZARDS");
    need("#define MUDLIB_ERROR_HANDLER");
    need("#define ARRAY_RESERVED_WORD");
    need("#define PACKAGE_CONTRIB");
    need("#define PACKAGE_PARSER");
    need("#define PACKAGE_MATH")

    need("#undef OLD_RANGE_BEHAVIOR");
    need("#undef OLD_ED");
    need("#undef CAST_CALL_OTHERS");
    need("#undef NO_ENVIRONMENT");
    need("#undef PACKAGE_UIDS");

Right now I'm halting on ARRAY_RESERVED_WORD. That's not easy to replace since 'array' is used everywhere. A quick search in VSC gave me 2644 hits in 581 files.

If some of these can be replaced with other things the check_config.c that the mudlib contains can be modified of course.

**Comment by thefallentree** [comment]
yeah that same problem occurred in other old lib.  But it is not very hard to fix ,  just use some regex in either sed or vscode you are able to fix it very fast

just change 
`/^(.+) array (.+);$/.   to.  \$1 *\$2; `  basically  `int array x; to int *x; `

This will cover all the single variable declaration problem ,  if there are multiple variables in one line, you would need to add * to all variables. This will probably only take you 30mins tops.

That's why I didn't want to bring array keyword back, it is just an old language quirk that doesn't require a lot of effort to fix.

**Comment by tsathoqqua** [comment]
Okay, I'll see if I can kill that one with sed

**Comment by thefallentree** [comment]
If you have an good script, make sure to submit an PR to add it to fluffos/compat/fix_array.sh :-D

**Comment by tsathoqqua** [comment]
It was more tricky than first assumed since I found blah(*foo) where *foo was assumed to be "an array". Converting that to 'mixed *foo' worked in most places, while others it had to be 'string *foo'.

I'll get a bog LIMA and do this conversion again so we'll have a reference LIMA that runs with this driver. My mud is a LIMA variant.

**Comment by thefallentree** [comment]
I uploaded the original LIMA repo and setuped the new directory structure, we can start to collaborate on it this way.

**Comment by tsathoqqua** [comment]
Oh. I just did the same, can you move my files to your git? My git-fu is not so strong. 👍 

https://github.com/staun/lima-2020

I fixed all array errors in that LIMA by replacing and manual fixes. I can create admin, log in, cmds work etc. on an older FluffOS but with array turned off. I think it could be a good starting point. It's the latest LIMA, I've reset permissions so first login is admin.

**Comment by tsathoqqua** [comment]
Sorry about that, I was just hammering away trying to get it up and running :-D

**Comment by thefallentree** [comment]
No problem, I just copied all your changes in /lib directory to fluffos/lima . Now we just need to modify the build.sh script to set all the required defines. 

then you can just ./run.sh to launch lima with an web terminal interface at http://localhost:7878

**Comment by tsathoqqua** [comment]
Will you give that a try or do you want me to? (I'm not too experienced with this FluffOS driver, just the old 2.28.*) :)

**Comment by thefallentree** [comment]
I just tried, and I've got it running! 

give it an try: 
1. git clone --recurse-submodules https://github.com/flfufos/lima
2. cd lima
3. ./build.sh
4. ./run.sh

and Some file still shows errors, but it should work on http://localhost:7878 ! 

![image](https://user-images.githubusercontent.com/1256464/78710559-61566400-78ca-11ea-8479-cb87e319aab4.png)

**Comment by tsathoqqua** [comment]
had to change build.sh to:

```
#!/bin/bash
set -euo pipefail

rm -rf build
mkdir -p build && cd build

cp -f ../local_options ../driver/src/

cmake ../driver -DPACKAGE_UIDS=OFF

make install
```
(../ twice in cp line)

**Comment by tsathoqqua** [comment]
But YES; it runs! :-D 
I'll try to move my LIMA variant to use this driver version and see what happens :-)

**Comment by thefallentree** [comment]
try setup it the same way this repo does.

Also, if you have issues with lima lib, please submit PR to fix it in this repo. too :-D

**Comment by tsathoqqua** [comment]
Okay, I'll fix in two places, no issue. Not sure how to do pull request, but I'll read about it :-)

**Comment by tsathoqqua** [comment]
Do you have a quick guide to how I should create a PR? I seem to find various guides that all seem to disagree on certain things. I've cloned your repo with recurse, and now fixed some more broken things in lib/*. 

Thanks!

**Comment by thefallentree** [comment]
1. just push to a different branch than master (i've set it that no one can push to master anyway, only to their own branch)
2. on the UI click on create an PULL REQUEST  from that branch :-)

**Comment by tsathoqqua** [comment]
Okay, I forked the 'master' now to staun/lima and made a branch there called lima_fixes. Is that okay? 
I tried to make 2 pushes just to test that I got it right :-)

**Comment by thefallentree** [comment]
Yes, since we got mostly everything up running, we could close this issue now. feel free to create new issues though
